version = 1

test_patterns = ["specs/*.ts"]

exclude_patterns = ["node_modues"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2020"
  module_system = "es-modules"
  environment = [
    "browser",
    "jest"
  ]

  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"
