name: ESLint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache Dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint
      uses: wearerequired/lint-action@v1.5.3
      with:
        # The GITHUB_TOKEN secret
        github_token: ${{ secrets.github_token }}
        # Enable or disable ESLint checks
        eslint: true
        # Directory where the ESLint command should be run
        eslint_dir: src
        # Extensions of files to check with ESLint
        eslint_extensions: ts,tsx
        # Args
        eslint_args: "-c ../.eslintrc.json"
